/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        canvas: "#b3ace9",
        "app-dark": "#161616",
        purple: "#6c5ce7",
        "purple-light": "#efedfb",
        "purple-soft": "#eae7fa",
        "purple-text": "#6c5ce7",
        "accent-orange": "#f4663b",
        ink: "#1f2030",
        "ink-soft": "#9a9aab",
        // Theme color mappings to global CSS variables
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        "primary-glow": "var(--primary-glow)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      fontFamily: {
        sans: ["Poppins_400Regular", "Poppins_500Medium", "Poppins_600SemiBold", "Poppins_700Bold", "System", "sans-serif"],
        display: ["SpaceGrotesk_700Bold", "System", "sans-serif"],
      },
      borderRadius: {
        lg: "16px",
        md: "14px",
        sm: "12px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
      },
    },
  },
  plugins: [],
}
